# Generated by Django 3.2.12 on 2022-03-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_place_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('pic', models.ImageField(upload_to='picture')),
                ('month', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.TextField()),
            ],
        ),
    ]
